ci/cd

diff --git a/.github/terraform.yml b/.github/terraform.yml
--- a/.github/terraform.yml
+++ b/.github/terraform.yml
@@ -1,7 +1,7 @@
 name: Deploy to ECS
 
 on:
-  #workflow_dispatch 
+  # workflow_dispatch:
   push:
     branches:
       - main
@@ -50,10 +50,15 @@ jobs:
           sudo apt-get install -y docker-ce docker-ce-cli containerd.io
           sudo usermod -aG docker $USER
 
-      - name: Set up .env file
+      - name: Create .env file
         run: |
-          echo "SUPABASE_URL=${{ secrets.SUPABASE_API_URL }}" > .env
-          echo "SUPABASE_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
+          cp .env.example .env
+          sed -i "s|your_supabase_url|${{ secrets.SUPABASE_URL }}|g" .env
+          sed -i "s|your_supabase_api_key|${{ secrets.SUPABASE_API_KEY }}|g" .env
+          sed -i "s|your_supabase_key|${{ secrets.SUPABASE_KEY }}|g" .env
+          # sed -i "s|your_key|${{ secrets.INFURA_KEY }}|g" .env
+          # sed -i "s|https://optimism-mainnet.infura.io/v3/your_key|${{ secrets.OPTIMISM_RPC_URL }}|g" .env
+          # sed -i "s|https://base-mainnet.infura.io/v3/your_key|${{ secrets.BASE_RPC_URL }}|g" .env
     
       - name: Build Docker Image
         # working-directory: airdrop-backend
@@ -68,8 +73,21 @@ jobs:
           docker push 058264122535.dkr.ecr.us-east-1.amazonaws.com/api/ionic:latest
 
       - name: Update Infra with latest deployment
+        id: update_infra
         run: |
           aws ecs update-service --cluster $ECS_CLUSTER_NAME --service $ECS_SERVICE_NAME --force-new-deployment
+
+      - name: Check deployment status
+        if: steps.update_infra.outcome != 'success'
+        run: |
+          echo "Deployment failed"
+          exit 1
+
+      - name: Wait for service stability
+        run: |
+          aws ecs wait services-stable \
+            --cluster $ECS_CLUSTER_NAME \
+            --services $ECS_SERVICE_NAME
 
       - name: Finalize
         if: steps.update_infra.outcome == 'success'
